workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest   

    scripts:
      - flutter pub get

      - name: Set dummy team
        script: |
          sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = ABCDE12345;/g' ios/Runner.xcodeproj/project.pbxproj

      - flutter build ios --release --no-codesign

      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

    artifacts:
      - app.ipa