workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest   

    scripts:
      - flutter pub get

      # 🔥 build بدون توقيع
      - flutter build ios --simulator --release

      # 🔥 تحويل الى ipa
      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphonesimulator/Runner.app Payload/
          zip -r app.ipa Payload

    artifacts:
      - app.ipa